from enum import StrEnum


class ProcurementStatus(StrEnum):
    AGREEMENT_PENDING_MANAGER = "AGREEMENT_PENDING_MANAGER"
    AGREEMENT_REVISION_REQUIRED = "AGREEMENT_REVISION_REQUIRED"
    PURCHASING = "PURCHASING"
    AWAITING_ACCEPTANCE = "AWAITING_ACCEPTANCE"
    COMPLETED = "COMPLETED"


class ProcurementLineType(StrEnum):
    EXISTING_ITEM = "EXISTING_ITEM"
    PROPOSED_ITEM = "PROPOSED_ITEM"


class ProcurementEventType(StrEnum):
    REQUEST_CREATED = "REQUEST_CREATED"
    REVISION_SUBMITTED = "REVISION_SUBMITTED"
    MANAGER_ACCEPTED = "MANAGER_ACCEPTED"
    CORRECTION_REQUESTED = "CORRECTION_REQUESTED"
    ASSIGNMENT_TAKEN = "ASSIGNMENT_TAKEN"
    ASSIGNMENT_TRANSFERRED = "ASSIGNMENT_TRANSFERRED"
    TRANSFERRED_TO_ACCEPTANCE = "TRANSFERRED_TO_ACCEPTANCE"
    LINE_BOUND = "LINE_BOUND"
    DISCREPANCY_REPORTED = "DISCREPANCY_REPORTED"
    COMPLETED = "COMPLETED"


ACTIVE_PROCUREMENT_STATUSES = frozenset(
    {
        ProcurementStatus.AGREEMENT_PENDING_MANAGER,
        ProcurementStatus.AGREEMENT_REVISION_REQUIRED,
        ProcurementStatus.PURCHASING,
        ProcurementStatus.AWAITING_ACCEPTANCE,
    }
)


STATUS_LABELS: dict[ProcurementStatus, str] = {
    ProcurementStatus.AGREEMENT_PENDING_MANAGER: "Ожидает менеджера",
    ProcurementStatus.AGREEMENT_REVISION_REQUIRED: "Требует корректировки",
    ProcurementStatus.PURCHASING: "В закупке",
    ProcurementStatus.AWAITING_ACCEPTANCE: "На приёмке",
    ProcurementStatus.COMPLETED: "Выполнена",
}
