"""Создать foundation-модель каталога и пять системных схем.

Revision ID: f4a5b6c7d8e9
Revises: e8f1a2b3c4d5
Create Date: 2026-09-01
"""

import uuid
from collections.abc import Sequence
from datetime import UTC, datetime
from typing import Any

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f4a5b6c7d8e9"
down_revision: str | Sequence[str] | None = "e8f1a2b3c4d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SEED_TIMESTAMP = datetime(2026, 9, 1, tzinfo=UTC)

CATEGORY_IDS = {
    "sfp": uuid.UUID("10000000-0000-4000-8000-000000000001"),
    "optics": uuid.UUID("10000000-0000-4000-8000-000000000002"),
    "power_cable": uuid.UUID("10000000-0000-4000-8000-000000000003"),
    "nic": uuid.UUID("10000000-0000-4000-8000-000000000004"),
    "disk": uuid.UUID("10000000-0000-4000-8000-000000000005"),
}


def _attribute(
    category_key: str,
    sequence: int,
    key: str,
    label: str,
    data_type: str,
    *,
    unit: str | None = None,
    required: bool = False,
    filterable: bool = False,
    searchable: bool = False,
    card_visible: bool = False,
    table_visible: bool = False,
    allowed_values: list[str] | None = None,
    validation_metadata: dict[str, Any] | None = None,
) -> dict[str, Any]:
    category_number = list(CATEGORY_IDS).index(category_key) + 1
    return {
        "id": uuid.UUID(
            f"2000000{category_number}-0000-4000-8000-{sequence:012d}"
        ),
        "category_id": CATEGORY_IDS[category_key],
        "key": key,
        "label": label,
        "data_type": data_type,
        "unit": unit,
        "required": required,
        "filterable": filterable,
        "searchable": searchable,
        "card_visible": card_visible,
        "detail_visible": True,
        "table_visible": table_visible,
        "excel_visible": True,
        "sort_order": sequence * 10,
        "filter_type": (
            "RANGE"
            if filterable and data_type in {"INTEGER", "DECIMAL"}
            else "EXACT"
            if filterable
            else "NONE"
        ),
        "allowed_values": allowed_values,
        "validation_metadata": validation_metadata,
        "is_system": True,
        "created_at": SEED_TIMESTAMP,
        "updated_at": SEED_TIMESTAMP,
    }


def _system_attributes() -> list[dict[str, Any]]:
    return [
        _attribute(
            "sfp",
            1,
            "form_factor",
            "Форм-фактор",
            "ENUM",
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            allowed_values=[
                "SFP",
                "SFP+",
                "SFP28",
                "QSFP+",
                "QSFP28",
                "QSFP56",
                "QSFP-DD",
            ],
        ),
        _attribute(
            "sfp",
            2,
            "speed_mbps",
            "Скорость",
            "INTEGER",
            unit="Mbps",
            required=True,
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            validation_metadata={"min": 1},
        ),
        _attribute(
            "sfp",
            3,
            "medium",
            "Среда",
            "ENUM",
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            allowed_values=["SMF", "MMF", "Copper", "DAC", "AOC"],
        ),
        _attribute(
            "sfp",
            4,
            "reach_class",
            "Класс дальности",
            "ENUM",
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            allowed_values=["SR", "LR", "ER", "ZR", "BiDi", "CWDM", "DWDM"],
        ),
        _attribute(
            "sfp",
            5,
            "reach_m",
            "Дальность",
            "INTEGER",
            unit="m",
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            validation_metadata={"min": 0},
        ),
        _attribute(
            "sfp",
            6,
            "connector",
            "Разъём",
            "ENUM",
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            allowed_values=["LC Duplex", "LC Simplex", "MPO/MTP", "RJ45"],
        ),
        _attribute(
            "sfp",
            7,
            "tx_wavelength_nm",
            "TX длина волны",
            "DECIMAL",
            unit="nm",
            filterable=True,
            searchable=True,
            validation_metadata={"min": 0},
        ),
        _attribute(
            "sfp",
            8,
            "rx_wavelength_nm",
            "RX длина волны",
            "DECIMAL",
            unit="nm",
            filterable=True,
            searchable=True,
            validation_metadata={"min": 0},
        ),
        _attribute(
            "sfp",
            9,
            "dom_ddm",
            "DOM/DDM",
            "BOOLEAN",
            filterable=True,
            card_visible=True,
            table_visible=True,
        ),
        _attribute(
            "sfp",
            10,
            "vendor_compatibility",
            "Совместимость с вендором",
            "TEXT",
            searchable=True,
            validation_metadata={"max_length": 2000},
        ),
        _attribute(
            "optics",
            1,
            "product_type",
            "Тип изделия",
            "TEXT",
            required=True,
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            validation_metadata={"max_length": 255},
        ),
        _attribute(
            "optics",
            2,
            "fiber_mode",
            "Тип волокна",
            "ENUM",
            required=True,
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            allowed_values=["SM", "MM"],
        ),
        _attribute(
            "optics",
            3,
            "fiber_standard",
            "Стандарт волокна",
            "ENUM",
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            allowed_values=["OS2", "OM2", "OM3", "OM4", "OM5"],
        ),
        _attribute(
            "optics",
            4,
            "connector_a",
            "Разъём A",
            "TEXT",
            required=True,
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            validation_metadata={"max_length": 255},
        ),
        _attribute(
            "optics",
            5,
            "polish_a",
            "Полировка A",
            "ENUM",
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            allowed_values=["UPC", "APC"],
        ),
        _attribute(
            "optics",
            6,
            "connector_b",
            "Разъём B",
            "TEXT",
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            validation_metadata={"max_length": 255},
        ),
        _attribute(
            "optics",
            7,
            "polish_b",
            "Полировка B",
            "ENUM",
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            allowed_values=["UPC", "APC"],
        ),
        _attribute(
            "optics",
            8,
            "fiber_count",
            "Количество волокон",
            "INTEGER",
            filterable=True,
            card_visible=True,
            table_visible=True,
            validation_metadata={"min": 1},
        ),
        _attribute(
            "optics",
            9,
            "length_m",
            "Длина",
            "DECIMAL",
            unit="m",
            required=True,
            filterable=True,
            card_visible=True,
            table_visible=True,
            validation_metadata={"min": 0},
        ),
        _attribute(
            "optics",
            10,
            "color",
            "Цвет",
            "TEXT",
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            validation_metadata={"max_length": 100},
        ),
        _attribute(
            "optics",
            11,
            "polarity",
            "Полярность",
            "TEXT",
            filterable=True,
            searchable=True,
            validation_metadata={"max_length": 100},
        ),
        _attribute(
            "power_cable",
            1,
            "connector_a",
            "Разъём A",
            "TEXT",
            required=True,
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            validation_metadata={"max_length": 255},
        ),
        _attribute(
            "power_cable",
            2,
            "connector_b",
            "Разъём B",
            "TEXT",
            required=True,
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            validation_metadata={"max_length": 255},
        ),
        _attribute(
            "power_cable",
            3,
            "length_m",
            "Длина",
            "DECIMAL",
            unit="m",
            required=True,
            filterable=True,
            card_visible=True,
            table_visible=True,
            validation_metadata={"min": 0},
        ),
        _attribute(
            "power_cable",
            4,
            "color",
            "Цвет",
            "TEXT",
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            validation_metadata={"max_length": 100},
        ),
        _attribute(
            "power_cable",
            5,
            "rated_current_a",
            "Номинальный ток",
            "DECIMAL",
            unit="A",
            filterable=True,
            card_visible=True,
            table_visible=True,
            validation_metadata={"min": 0},
        ),
        _attribute(
            "power_cable",
            6,
            "rated_voltage_v",
            "Номинальное напряжение",
            "INTEGER",
            unit="V",
            filterable=True,
            table_visible=True,
            validation_metadata={"min": 0},
        ),
        _attribute(
            "nic",
            1,
            "port_count",
            "Количество портов",
            "INTEGER",
            required=True,
            filterable=True,
            card_visible=True,
            table_visible=True,
            validation_metadata={"min": 1},
        ),
        _attribute(
            "nic",
            2,
            "port_speed_mbps",
            "Скорость порта",
            "INTEGER",
            unit="Mbps",
            required=True,
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            validation_metadata={"min": 1},
        ),
        _attribute(
            "nic",
            3,
            "media_type",
            "Тип порта",
            "ENUM",
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            allowed_values=["RJ45", "SFP+", "SFP28", "QSFP+", "QSFP28"],
        ),
        _attribute(
            "nic",
            4,
            "pcie_generation",
            "Поколение PCIe",
            "TEXT",
            filterable=True,
            searchable=True,
            table_visible=True,
            validation_metadata={"max_length": 32},
        ),
        _attribute(
            "nic",
            5,
            "pcie_lanes",
            "Линии PCIe",
            "INTEGER",
            filterable=True,
            table_visible=True,
            validation_metadata={"min": 1},
        ),
        _attribute(
            "nic",
            6,
            "protocol",
            "Протокол",
            "ENUM",
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            allowed_values=["Ethernet", "Fibre Channel", "InfiniBand"],
        ),
        _attribute(
            "nic",
            7,
            "bracket",
            "Планка",
            "ENUM",
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            allowed_values=["full_profile", "low_profile", "unknown"],
        ),
        _attribute(
            "nic",
            8,
            "sriov",
            "SR-IOV",
            "BOOLEAN",
            filterable=True,
        ),
        _attribute(
            "nic",
            9,
            "rdma_roce",
            "RDMA / RoCE",
            "BOOLEAN",
            filterable=True,
        ),
        _attribute(
            "disk",
            1,
            "drive_type",
            "Тип накопителя",
            "ENUM",
            required=True,
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            allowed_values=["HDD", "SSD", "NVMe"],
        ),
        _attribute(
            "disk",
            2,
            "capacity_bytes",
            "Ёмкость",
            "INTEGER",
            unit="bytes",
            required=True,
            filterable=True,
            card_visible=True,
            table_visible=True,
            validation_metadata={"min": 1},
        ),
        _attribute(
            "disk",
            3,
            "form_factor",
            "Форм-фактор",
            "ENUM",
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            allowed_values=["2.5", "3.5", "M.2", "U.2", "U.3"],
        ),
        _attribute(
            "disk",
            4,
            "interface",
            "Интерфейс",
            "ENUM",
            required=True,
            filterable=True,
            searchable=True,
            card_visible=True,
            table_visible=True,
            allowed_values=["SATA", "SAS", "NVMe"],
        ),
        _attribute(
            "disk",
            5,
            "interface_speed_mbps",
            "Скорость интерфейса",
            "INTEGER",
            unit="Mbps",
            filterable=True,
            searchable=True,
            table_visible=True,
            validation_metadata={"min": 1},
        ),
        _attribute(
            "disk",
            6,
            "rpm",
            "Скорость вращения",
            "INTEGER",
            unit="rpm",
            filterable=True,
            table_visible=True,
            validation_metadata={"min": 1},
        ),
        _attribute(
            "disk",
            7,
            "sector_format",
            "Формат сектора",
            "TEXT",
            filterable=True,
            searchable=True,
            validation_metadata={"max_length": 100},
        ),
        _attribute(
            "disk",
            8,
            "endurance",
            "Ресурс",
            "TEXT",
            searchable=True,
            validation_metadata={"max_length": 255},
        ),
    ]


def upgrade() -> None:
    op.create_table(
        "categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_accounting_mode", sa.String(length=8), nullable=False),
        sa.Column(
            "sort_order",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "is_system",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(key) <> ''",
            name=op.f("ck_categories_key_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(display_name) <> ''",
            name=op.f("ck_categories_display_name_not_blank"),
        ),
        sa.CheckConstraint(
            "default_accounting_mode IN ('QUANTITY', 'SERIAL')",
            name=op.f("ck_categories_default_accounting_mode"),
        ),
        sa.CheckConstraint(
            "sort_order >= 0",
            name=op.f("ck_categories_sort_order_non_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("key", name=op.f("uq_categories_key")),
    )

    op.create_table(
        "manufacturers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(name) <> ''",
            name=op.f("ck_manufacturers_name_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(normalized_name) <> ''",
            name=op.f("ck_manufacturers_normalized_name_not_blank"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manufacturers")),
        sa.UniqueConstraint(
            "normalized_name",
            name=op.f("uq_manufacturers_normalized_name"),
        ),
    )

    op.create_table(
        "category_attributes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("data_type", sa.String(length=7), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=True),
        sa.Column(
            "required",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "filterable",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "searchable",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "card_visible",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "detail_visible",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "table_visible",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "excel_visible",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "sort_order",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "filter_type",
            sa.String(length=5),
            server_default=sa.text("'NONE'"),
            nullable=False,
        ),
        sa.Column(
            "allowed_values",
            postgresql.JSONB(astext_type=sa.Text(), none_as_null=True),
            nullable=True,
        ),
        sa.Column(
            "validation_metadata",
            postgresql.JSONB(astext_type=sa.Text(), none_as_null=True),
            nullable=True,
        ),
        sa.Column(
            "is_system",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(key) <> ''",
            name=op.f("ck_category_attributes_key_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(label) <> ''",
            name=op.f("ck_category_attributes_label_not_blank"),
        ),
        sa.CheckConstraint(
            "data_type IN ('TEXT', 'INTEGER', 'DECIMAL', 'BOOLEAN', 'ENUM')",
            name=op.f("ck_category_attributes_data_type"),
        ),
        sa.CheckConstraint(
            "filter_type IN ('NONE', 'EXACT', 'RANGE')",
            name=op.f("ck_category_attributes_filter_type"),
        ),
        sa.CheckConstraint(
            "(filterable AND filter_type <> 'NONE') "
            "OR (NOT filterable AND filter_type = 'NONE')",
            name=op.f("ck_category_attributes_filter_configuration"),
        ),
        sa.CheckConstraint(
            "CASE WHEN data_type = 'ENUM' THEN "
            "allowed_values IS NOT NULL "
            "AND jsonb_typeof(allowed_values) = 'array' "
            "AND jsonb_array_length(allowed_values) > 0 "
            "ELSE allowed_values IS NULL END",
            name=op.f("ck_category_attributes_allowed_values_match_data_type"),
        ),
        sa.CheckConstraint(
            "validation_metadata IS NULL "
            "OR jsonb_typeof(validation_metadata) = 'object'",
            name=op.f("ck_category_attributes_validation_metadata_object"),
        ),
        sa.CheckConstraint(
            "sort_order >= 0",
            name=op.f("ck_category_attributes_sort_order_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_category_attributes_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category_attributes")),
        sa.UniqueConstraint(
            "category_id",
            "key",
            name="uq_category_attributes_category_id_key",
        ),
        sa.UniqueConstraint(
            "id",
            "category_id",
            name="uq_category_attributes_id_category_id",
        ),
    )

    op.create_table(
        "items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("manufacturer_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column("normalized_model", sa.String(length=255), nullable=True),
        sa.Column("manufacturer_part_number", sa.String(length=255), nullable=True),
        sa.Column(
            "normalized_manufacturer_part_number",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column("internal_code", sa.String(length=128), nullable=True),
        sa.Column("normalized_internal_code", sa.String(length=128), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("accounting_mode", sa.String(length=8), nullable=False),
        sa.Column(
            "status",
            sa.String(length=8),
            server_default=sa.text("'ACTIVE'"),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("datasheet_url", sa.String(length=2048), nullable=True),
        sa.Column("technical_data_source", sa.Text(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(name) <> ''",
            name=op.f("ck_items_name_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(normalized_name) <> ''",
            name=op.f("ck_items_normalized_name_not_blank"),
        ),
        sa.CheckConstraint(
            "accounting_mode IN ('QUANTITY', 'SERIAL')",
            name=op.f("ck_items_accounting_mode"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'ARCHIVED')",
            name=op.f("ck_items_status"),
        ),
        sa.CheckConstraint(
            "(status = 'ACTIVE' AND archived_at IS NULL) "
            "OR (status = 'ARCHIVED' AND archived_at IS NOT NULL)",
            name=op.f("ck_items_archive_state"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_items_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["manufacturer_id"],
            ["manufacturers.id"],
            name=op.f("fk_items_manufacturer_id_manufacturers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
        sa.UniqueConstraint(
            "id",
            "category_id",
            name="uq_items_id_category_id",
        ),
        sa.UniqueConstraint(
            "normalized_internal_code",
            name=op.f("uq_items_normalized_internal_code"),
        ),
    )
    op.create_index(
        op.f("ix_items_manufacturer_id"),
        "items",
        ["manufacturer_id"],
        unique=False,
    )
    op.create_index(
        "ix_items_category_id_status_normalized_name",
        "items",
        ["category_id", "status", "normalized_name"],
        unique=False,
    )
    op.create_index(
        "ix_items_status_normalized_name",
        "items",
        ["status", "normalized_name"],
        unique=False,
    )
    op.create_index(
        "ix_items_duplicate_mpn",
        "items",
        [
            "category_id",
            "manufacturer_id",
            "normalized_manufacturer_part_number",
        ],
        unique=False,
    )
    op.create_index(
        "ix_items_duplicate_name_model",
        "items",
        ["category_id", "manufacturer_id", "normalized_name", "normalized_model"],
        unique=False,
    )

    op.create_table(
        "item_attribute_values",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("category_attribute_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("text_value", sa.Text(), nullable=True),
        sa.Column("integer_value", sa.BigInteger(), nullable=True),
        sa.Column("decimal_value", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("boolean_value", sa.Boolean(), nullable=True),
        sa.Column("enum_value", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "num_nonnulls(text_value, integer_value, decimal_value, "
            "boolean_value, enum_value) = 1",
            name=op.f("ck_item_attribute_values_exactly_one_typed_value"),
        ),
        sa.CheckConstraint(
            "text_value IS NULL OR btrim(text_value) <> ''",
            name=op.f("ck_item_attribute_values_text_value_not_blank"),
        ),
        sa.CheckConstraint(
            "enum_value IS NULL OR btrim(enum_value) <> ''",
            name=op.f("ck_item_attribute_values_enum_value_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id", "category_id"],
            ["items.id", "items.category_id"],
            name=op.f("fk_item_attribute_values_item_id_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_attribute_id", "category_id"],
            ["category_attributes.id", "category_attributes.category_id"],
            name=op.f(
                "fk_item_attribute_values_category_attribute_id_category_attributes"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_attribute_values")),
        sa.UniqueConstraint(
            "item_id",
            "category_attribute_id",
            name="uq_item_attribute_values_item_id_category_attribute_id",
        ),
    )
    op.create_index(
        "ix_item_attribute_values_category_attribute_id",
        "item_attribute_values",
        ["category_attribute_id"],
        unique=False,
    )

    category_table = sa.table(
        "categories",
        sa.column("id", sa.Uuid()),
        sa.column("key", sa.String()),
        sa.column("display_name", sa.String()),
        sa.column("description", sa.Text()),
        sa.column("default_accounting_mode", sa.String()),
        sa.column("sort_order", sa.Integer()),
        sa.column("is_system", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        category_table,
        [
            {
                "id": CATEGORY_IDS["sfp"],
                "key": "sfp",
                "display_name": "SFP / оптические трансиверы",
                "description": "Каталожные позиции оптических и медных трансиверов.",
                "default_accounting_mode": "QUANTITY",
                "sort_order": 10,
                "is_system": True,
                "created_at": SEED_TIMESTAMP,
                "updated_at": SEED_TIMESTAMP,
            },
            {
                "id": CATEGORY_IDS["optics"],
                "key": "optics",
                "display_name": "Оптические кабели",
                "description": "Патч-корды, пигтейлы и аналогичная оптическая кабельная продукция.",
                "default_accounting_mode": "QUANTITY",
                "sort_order": 20,
                "is_system": True,
                "created_at": SEED_TIMESTAMP,
                "updated_at": SEED_TIMESTAMP,
            },
            {
                "id": CATEGORY_IDS["power_cable"],
                "key": "power_cable",
                "display_name": "Кабели питания",
                "description": "Кабели и шнуры электропитания.",
                "default_accounting_mode": "QUANTITY",
                "sort_order": 30,
                "is_system": True,
                "created_at": SEED_TIMESTAMP,
                "updated_at": SEED_TIMESTAMP,
            },
            {
                "id": CATEGORY_IDS["nic"],
                "key": "nic",
                "display_name": "Сетевые карты",
                "description": "Сетевые интерфейсные карты и адаптеры.",
                "default_accounting_mode": "SERIAL",
                "sort_order": 40,
                "is_system": True,
                "created_at": SEED_TIMESTAMP,
                "updated_at": SEED_TIMESTAMP,
            },
            {
                "id": CATEGORY_IDS["disk"],
                "key": "disk",
                "display_name": "Диски / накопители",
                "description": "HDD, SSD и NVMe накопители как каталожные позиции.",
                "default_accounting_mode": "SERIAL",
                "sort_order": 50,
                "is_system": True,
                "created_at": SEED_TIMESTAMP,
                "updated_at": SEED_TIMESTAMP,
            },
        ],
    )

    attribute_table = sa.table(
        "category_attributes",
        sa.column("id", sa.Uuid()),
        sa.column("category_id", sa.Uuid()),
        sa.column("key", sa.String()),
        sa.column("label", sa.String()),
        sa.column("data_type", sa.String()),
        sa.column("unit", sa.String()),
        sa.column("required", sa.Boolean()),
        sa.column("filterable", sa.Boolean()),
        sa.column("searchable", sa.Boolean()),
        sa.column("card_visible", sa.Boolean()),
        sa.column("detail_visible", sa.Boolean()),
        sa.column("table_visible", sa.Boolean()),
        sa.column("excel_visible", sa.Boolean()),
        sa.column("sort_order", sa.Integer()),
        sa.column("filter_type", sa.String()),
        sa.column("allowed_values", postgresql.JSONB(none_as_null=True)),
        sa.column("validation_metadata", postgresql.JSONB(none_as_null=True)),
        sa.column("is_system", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(attribute_table, _system_attributes())


def downgrade() -> None:
    op.drop_index(
        "ix_item_attribute_values_category_attribute_id",
        table_name="item_attribute_values",
    )
    op.drop_table("item_attribute_values")

    op.drop_index("ix_items_duplicate_name_model", table_name="items")
    op.drop_index("ix_items_duplicate_mpn", table_name="items")
    op.drop_index("ix_items_status_normalized_name", table_name="items")
    op.drop_index(
        "ix_items_category_id_status_normalized_name",
        table_name="items",
    )
    op.drop_index(op.f("ix_items_manufacturer_id"), table_name="items")
    op.drop_table("items")

    op.drop_table("category_attributes")
    op.drop_table("manufacturers")
    op.drop_table("categories")
